spring:
  application:
    name: storylens
  ai:
    model:
      embedding: none
    openai:
      api-key: ${LLM_API_KEY}
      base-url: https://api.openai.com/v1
      chat:
        completions-path: /chat/completions
